openapi: 3.0.0
info:
  title: ReqRes API
  description: Fake API for testing and prototyping
  version: "1.0"

servers:
  - url: https://reqres.in/api

paths:
  /users:
    get:
      summary: List users
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: A paged list of users

    post:
      summary: Create a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created

  /users/{id}:
    get:
      summary: Get a single user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: User found
        '404':
          description: User not found

    put:
      summary: Update user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated

    delete:
      summary: Delete user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: User deleted

  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: Registration successful
        '400':
          description: Missing data

  /login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Auth'
      responses:
        '200':
          description: Login successful
        '400':
          description: Login failed

components:
  schemas:
    User:
      type: object
      properties:
        name:
          type: string
        job:
          type: string
      required:
        - name
        - job

    Auth:
      type: object
      properties:
        email:
          type: string
          example: eve.holt@reqres.in
        password:
          type: string
          example: pistol
      required:
        - email
        - password
